# Generated by Django 4.2.11 on 2024-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='success_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
